name: "Check shell script"

on:
  push:
    branches:
      - develop

jobs:
  shellcheck:
    name: Run Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Shellcheck
        uses: ludeeus/action-shellcheck@master

  discord-notify:
    name: Notify Discord
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Discord Commits
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          include-extras: true
          embed: |
            {
              "title": "{{ commit.title }}",
              "description": "{{ commit.description }}",
              "url": "{{ commit.url }}",
              "color": 3447003,
              "author": {
                "name": "{{ commit.author.name }}",
                "icon_url": "https://github.com/{{ commit.author.username }}.png",
                "url": "https://github.com/{{ commit.author.username }}"
              },
              "footer": {
                "text": "Commit ID: {{ commit.id }}"
              },
              "timestamp": "{{ commit.timestamp }}"
            }
